## Understanding JAX’s execution environment and memory model

### 1–5 → Environment Awareness

## ✅ Exercise 1 — Install JAX

In [1]:
!pip install jax jaxlib -q


[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip


## ✅ Exercise 2 — Import JAX

In [2]:
import jax  # CPU only
import jax.numpy as jnp # works on CPU/GPU/TPU

## ✅ Exercise 3 — Check Version

In [3]:
jax.__version__

'0.9.1'

## ✅ Exercise 4 — Check Backend

In [4]:
jax.default_backend() # cpu, gpu, tpu

'cpu'

## ✅ Exercise 5 — Check Devices

In [5]:
jax.devices()

[CpuDevice(id=0)]

### 6–8 → What is a JAX Array?

## ✅ Exercise 6 — Create a JAX Array

In [6]:
data = jnp.array([10, 1, 24]) # A NumPy array that can move to accelerators.
data

Array([10,  1, 24], dtype=int32)

## ✅ Exercise 7 — Check Type

In [7]:
type(data)

jaxlib._jax.ArrayImpl

## ✅ Exercise 8 — Check Shape

In [8]:
data.shape

(3,)

## ✅ Exercise 9 — Move Array to Host (CPU Memory)

### 9–10 → Host vs Device Memory

In [9]:
data_host = jax.device_get(data)
data_host

array([10,  1, 24], dtype=int32)

## ✅ Exercise 10 — Move Data to Device

In [10]:
data_device = jax.device_put(data_host)
data_device

Array([10,  1, 24], dtype=int32)