# Understanding JAX's Execution Environment and Memory Model

This notebook explores the fundamental concepts of JAX, including its execution environment, memory model, and device management.

## Environment Awareness (Exercises 1-5)

In this section, we'll set up JAX and explore the execution environment.

### ✅ Exercise 1 — Install JAX

First, let's install JAX and its supporting library jaxlib.

In [1]:
!pip install jax jaxlib -q


[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip


### ✅ Exercise 2 — Import JAX

Now let's import JAX and JAX NumPy. The main difference is that `jax.numpy` operations can be executed on CPU, GPU, or TPU, while regular NumPy only runs on CPU.

In [2]:
import jax  # CPU only
import jax.numpy as jnp # works on CPU/GPU/TPU

### ✅ Exercise 3 — Check Version

Let's verify our JAX installation by checking the version.

In [3]:
jax.__version__

'0.9.1'

### ✅ Exercise 4 — Check Backend

JAX automatically detects and uses the available hardware backend. This could be 'cpu', 'gpu', or 'tpu'.

In [4]:
jax.default_backend() # cpu, gpu, tpu

'cpu'

### ✅ Exercise 5 — Check Available Devices

Let's see what computational devices are available to JAX.

In [5]:
jax.devices()

[CpuDevice(id=0)]

## What is a JAX Array? (Exercises 6-8)

JAX arrays are similar to NumPy arrays but with additional capabilities for accelerator execution and automatic differentiation.

### ✅ Exercise 6 — Create a JAX Array

Let's create our first JAX array. Notice it looks similar to a NumPy array, but it's designed to work across different hardware backends.

In [6]:
data = jnp.array([10, 1, 24]) # A NumPy array that can move to accelerators.
data

Array([10,  1, 24], dtype=int32)

### ✅ Exercise 7 — Check Array Type

JAX arrays have a different internal type than NumPy arrays, even though they behave similarly.

In [7]:
type(data)

jaxlib._jax.ArrayImpl

### ✅ Exercise 8 — Check Array Shape

Like NumPy arrays, JAX arrays have shape information that defines their dimensions.

In [8]:
data.shape

(3,)

### ✅ Exercise 9 — Move Array to Host (CPU Memory)

Sometimes we need to move data from device memory back to host memory, for example to use with regular NumPy or other libraries.

## Host vs Device Memory (Exercises 9-10)

Understanding the difference between host (CPU) memory and device (GPU/TPU) memory is crucial for efficient JAX programming.

In [9]:
data_host = jax.device_get(data)
data_host

array([10,  1, 24], dtype=int32)

### ✅ Exercise 10 — Move Data to Device

Let's move the data back to device memory. This is where JAX operations will be executed for optimal performance.

In [10]:
data_device = jax.device_put(data_host)
data_device

Array([10,  1, 24], dtype=int32)