# Immutability + Functional Updates + Matrix Operations

This notebook explores JAX's immutability principles and functional programming approach to array operations, including matrix manipulations.

## Why Immutability?

### 🧠 The Core Concept

If arrays could change in-place:
- **JIT compilation** becomes unpredictable
- **Gradients** become messy  
- **Parallelization** breaks

So JAX forces:
- **No in-place mutation**
- **Always return a new array**
- **Functional programming style**

This ensures reproducible computations and enables powerful optimizations.

In [1]:
# Import JAX libraries
import jax  # Main JAX library
import jax.numpy as jnp  # JAX NumPy API (works on CPU/GPU/TPU)

### ✅ Exercise 11 — Create a 2D Matrix

Let's start by creating a 2D JAX array to work with throughout these exercises.

In [2]:
data = jnp.array([[10, 1, 24],
                  [20, 15, 14]])
data

Array([[10,  1, 24],
       [20, 15, 14]], dtype=int32)

In [3]:
data.shape

(2, 3)

### ✅ Exercise 12 — Transpose

Transposing a matrix swaps its rows and columns. This is a fundamental operation in linear algebra.

In [4]:
dataT = data.T
dataT

Array([[10, 20],
       [ 1, 15],
       [24, 14]], dtype=int32)

In [5]:
dataT.shape

(3, 2)

### ✅ Exercise 13 — Indexing

Accessing individual elements in a JAX array works just like in NumPy, using zero-based indexing.

In [6]:
value = data[0, 2]
value

Array(24, dtype=int32)

### ✅ Exercise 14 — Update a Value

This demonstrates the key difference between NumPy and JAX. NumPy allows in-place modification, while JAX requires creating a new array.

In [7]:
import numpy as np
data_np = np.array(data)
data_np[1,1] = 100 # numpy way
data_np

array([[ 10,   1,  24],
       [ 20, 100,  14]], dtype=int32)

In [8]:
data = data.at[1, 1].set(100)
data

Array([[ 10,   1,  24],
       [ 20, 100,  14]], dtype=int32)

### ✅ Exercise 15 — Add to an Element

JAX provides functional methods like `.add()` that return a new array with the modification applied.

In [9]:
data = data.at[0, 0].add(41)
data

Array([[ 51,   1,  24],
       [ 20, 100,  14]], dtype=int32)

### ✅ Exercise 16 — Reduce Along Axis

Reduction operations like `min()` can be performed along specific axes to collapse dimensions.

In [10]:
mins = data.min(axis=1)
mins

Array([ 1, 14], dtype=int32)

### ✅ Exercise 17 — Select First Row

Slicing operations work similarly to NumPy, allowing you to extract subsets of the data.

In [11]:
data_select = data[0]
data_select

Array([51,  1, 24], dtype=int32)

### ✅ Exercise 18 — Append Row

Since JAX arrays are immutable, we use functions like `vstack` that return new arrays with the requested modifications.

In [12]:
data = jnp.vstack([data, data_select])
data

Array([[ 51,   1,  24],
       [ 20, 100,  14],
       [ 51,   1,  24]], dtype=int32)

In [13]:
data

Array([[ 51,   1,  24],
       [ 20, 100,  14],
       [ 51,   1,  24]], dtype=int32)

## Bonus — Append Column

### Understanding Array Broadcasting

This demonstrates how to add a column to an existing matrix using proper broadcasting techniques.

In [14]:
# Broadcasting: [:, None] converts 1D array (3,) to 2D column vector (3, 1)
# This enables horizontal concatenation with the 2D matrix 'data'
# Final shape: (3 rows, 3+1 columns) = (3, 4)

data_hstack = jnp.hstack([data, data_select[:, None]])
data_hstack

Array([[ 51,   1,  24,  51],
       [ 20, 100,  14,   1],
       [ 51,   1,  24,  24]], dtype=int32)

### ✅ Exercise 19 — Matrix Multiplication

Matrix multiplication follows the rule: `(m × n) dot (n × p) = (m × p)`. This is a fundamental operation in linear algebra and deep learning.

In [15]:
# (m × n) dot (n × p) = (m × p)
data_prod = jnp.dot(data, dataT)
data_prod

Array([[1087, 1371],
       [ 636, 2096],
       [1087, 1371]], dtype=int32)

### ✅ Exercise 20 — Change Data Type

Sometimes you need to change the data type of arrays for memory efficiency or numerical precision requirements.

In [16]:
data_prod = jnp.array(data_prod, dtype=jnp.float16)
data_prod

Array([[1.087e+03, 1.371e+03],
       [6.360e+02, 2.096e+03],
       [1.087e+03, 1.371e+03]], dtype=float16)

## Conclusion

### NumPy vs JAX Mindset

**NumPy mindset:**
- Modify arrays in-place
- Mutable data structures

**JAX mindset:**
- Return transformed arrays
- Immutable data structures
- Functional programming approach

This immutability enables JAX's powerful features like JIT compilation, automatic differentiation, and parallel execution.