## Immutability + Functional Updates + Matrix Operations

🧠 Why Immutability?

If arrays could change:

JIT compilation becomes unpredictable

Gradients become messy

Parallelization breaks

So JAX forces:

No in-place mutation.

You always return a new array.

Functional programming style.

In [1]:
import jax  # CPU only
import jax.numpy as jnp # works on CPU/GPU/TPU

## ✅ Exercise 11 — Create a 2D Matrix

In [2]:
data = jnp.array([[10, 1, 24],
                  [20, 15, 14]])
data

Array([[10,  1, 24],
       [20, 15, 14]], dtype=int32)

In [3]:
data.shape

(2, 3)

## ✅ Exercise 12 — Transpose

In [4]:
dataT = data.T
dataT

Array([[10, 20],
       [ 1, 15],
       [24, 14]], dtype=int32)

In [5]:
dataT.shape

(3, 2)

## ✅ Exercise 13 — Indexing

In [6]:
value = data[0, 2]
value

Array(24, dtype=int32)

## ✅ Exercise 14 — Update a Value

In [7]:
import numpy as np
data_np = np.array(data)
data_np[1,1] = 100 # numpy way
data_np

array([[ 10,   1,  24],
       [ 20, 100,  14]], dtype=int32)

In [8]:
data = data.at[1, 1].set(100)
data

Array([[ 10,   1,  24],
       [ 20, 100,  14]], dtype=int32)

## ✅ Exercise 15 — Add to an Element

In [9]:
data = data.at[0, 0].add(41)
data

Array([[ 51,   1,  24],
       [ 20, 100,  14]], dtype=int32)

## ✅ Exercise 16 — Reduce Along Axis

In [10]:
mins = data.min(axis=1)
mins

Array([ 1, 14], dtype=int32)

## ✅ Exercise 17 — Select First Row

In [11]:
data_select = data[0]
data_select

Array([51,  1, 24], dtype=int32)

## ✅ Exercise 18 — Append Row

In [12]:
data = jnp.vstack([data, data_select])
data

Array([[ 51,   1,  24],
       [ 20, 100,  14],
       [ 51,   1,  24]], dtype=int32)

In [13]:
data

Array([[ 51,   1,  24],
       [ 20, 100,  14],
       [ 51,   1,  24]], dtype=int32)

In [14]:
# [:, None] adds a new axis at the end → turns (3,) → (3, 1)
# Now both inputs are 2D → concatenation along columns works
# Result shape: (3, 3 + 1) = (3, 4)

data_hstack = jnp.hstack([data, data_select[:,None]])
data_hstack

Array([[ 51,   1,  24,  51],
       [ 20, 100,  14,   1],
       [ 51,   1,  24,  24]], dtype=int32)

## ✅ Exercise 19 — Matrix Multiplication

In [15]:
# (m × n) dot (n × p) = (m × p)
data_prod = jnp.dot(data, dataT)
data_prod

Array([[1087, 1371],
       [ 636, 2096],
       [1087, 1371]], dtype=int32)

## ✅ Exercise 20 — Change dtype

In [16]:
data_prod = jnp.array(data_prod, dtype=jnp.float16)
data_prod

Array([[1.087e+03, 1.371e+03],
       [6.360e+02, 2.096e+03],
       [1.087e+03, 1.371e+03]], dtype=float16)

## Conclusion

NumPy mindset:

Modify arrays.

JAX mindset:

Return transformed arrays.