## Pure functional randomness in JAX

🧠 First Principle: Why Randomness Is Special in JAX

In NumPy:

np.random.rand()
np.random.rand()

Each call gives new random numbers.

Because NumPy has global mutable state.

JAX does NOT allow hidden state.

So JAX uses:

Explicit randomness via PRNG keys.

You control randomness manually.

In [2]:
import jax
import jax.numpy as jnp

## ✅ Exercise 21 — Create a PRNG Key

Because JAX is functional.

Instead of:

“Give me randomness”

You say:

“Here is a key. Use it.”

No hidden global randomness.

This makes:

JIT safe

Parallel safe

Reproducible

In [3]:
key = jax.random.PRNGKey(100) # This key is just an array, it contains state
key

Array([  0, 100], dtype=uint32)

## ✅ Exercise 22 — Split the Key

In [4]:
key, subkey = jax.random.split(key) # If you reuse the same key → you get same random numbers.
key, subkey # You never reuse keys  # Old key → split → new key + usable key

(Array([ 701046466, 2104227382], dtype=uint32),
 Array([2213033797, 2583756506], dtype=uint32))

## ✅ Exercise 23 — Split Into Many Keys

In [5]:
key_1, key_2, key_3, key_4, key_5, key_6, key_7 = jax.random.split(key, num=7) # One key per random operation.
key_1, key_2, key_3, key_4, key_5, key_6, key_7

(Array([3549270403, 1145628597], dtype=uint32),
 Array([1315821631, 2840677502], dtype=uint32),
 Array([1953597499, 2148997509], dtype=uint32),
 Array([1420903369,  369168748], dtype=uint32),
 Array([ 242814072, 1159027379], dtype=uint32),
 Array([ 194610812, 2464920650], dtype=uint32),
 Array([3641069794,   35145164], dtype=uint32))

## ✅ Exercise 24 — Random Permutation

In [7]:
sample_data = jnp.array([10, 1, 24, 20, 15, 14])
data_permutation = jax.random.permutation(key_1, sample_data) # No key → no randomness.
data_permutation

Array([15, 20, 10, 14,  1, 24], dtype=int32)

## ✅ Exercise 25 — Random Choice

In [8]:
random_selection = jax.random.choice(key_2, sample_data)
random_selection

Array(15, dtype=int32)

## ✅ Exercise 26 — Random Integer

In [10]:
sample_int = jax.random.randint(
    key_3,
    shape=(1,),  # output_shape
    minval=10, # min_val
    maxval=24 # max_val
)
sample_int

Array([20], dtype=int32)

## ✅ Exercise 27 — Uniform Distribution

In [12]:
sample_uniform = jax.random.uniform( # Equal probability between 1 and 2.
    key_4,
    shape=(2,),
    minval=1,
    maxval=2
)
sample_uniform

Array([1.2547921, 1.2823569], dtype=float32)

## ✅ Exercise 28 — Bernoulli

In [14]:
sample_bernoulli = jax.random.bernoulli( # Bernoulli = coin flip.
    key_5,
    shape=(3,)
)
sample_bernoulli

Array([ True,  True,  True], dtype=bool)

## ✅ Exercise 29 — Poisson

In [15]:
sample_poisson = jax.random.poisson(
    key_6,
    shape=(2, 3),
    lam=100 # lam = expected count.
)
sample_poisson

W0303 17:30:42.972430 9945008 cpp_gen_intrinsics.cc:74] Empty bitcode string provided for eigen. Optimizations relying on this IR will be disabled.


Array([[ 94, 109, 106],
       [ 89, 100,  84]], dtype=int32)

## ✅ Exercise 30 — Normal Distribution

In [16]:
sample_normal = jax.random.normal(
    key_7,
    shape=(2, 3, 4)
)
sample_normal

Array([[[ 0.34660995,  0.02455962,  1.0251855 ,  0.763851  ],
        [-2.0041497 ,  0.1554214 , -1.7528274 ,  2.0635715 ],
        [-0.17306615,  1.4471363 ,  0.05802692, -0.19730496]],

       [[ 0.31210348,  0.67494154, -0.5323124 ,  0.08658653],
        [-0.8526911 ,  0.03244016,  0.29185736,  1.2332078 ],
        [ 1.6374227 ,  0.33908826, -1.8585606 ,  0.7492276 ]]],      dtype=float32)

### Conclusion

The theme is:

Explicit, functional randomness.

JAX forces you to think like this:

Instead of:

“Give me randomness”

You do:

“Here is a key. Transform it.”

This is:

Deterministic

Reproducible

Parallel safe

JIT safe